### ISSUE TITLE
toPDF() requires gc() call 

### ISSUE THREAD

**Issue by mespe** [duncantl/Rtesseract#6]
Creating a pdf using toPDF() results in a "damaged pdf" file unless the call to toPDF() is followed by gc().

**Comment by dsidavis** [comment]
Fix pushed.  Need to remove renderer() in the function before calling gc().
If the user creates the renderer separately, she will have to call gc() after it goes out of scope.

**Comment by mespe** [comment]
Confirmed fixed.
